npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN}'

npmScopes:
  mhirba:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-sources.cjs
