name: CI

# Trigger the workflow on push or pull request,
on: [push]

jobs:
  build:
    name: Objectif Lune
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@mhirba'
      - run: yarn
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn test
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
